name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x

    - uses: actions/checkout@v2
      with:
        repository: 'macnev2013/github-actions-docker-sample'
        ref: '${GITHUB_REF_SLUG}'

    - name: Testing variables
      run: |
        ls -la
        pwd
